services:
  werewolf-bot:
    image: werewolf-dev:latest
    build:
      context: ./
      dockerfile: Dev.Dockerfile
    volumes:
      - ./:/home/node/app
    env_file: ".env"
    environment:
      MONGO_URI: "mongodb://sa:password@db"
      MONGODB_NAME: "werewolf"
      TESTING_MODE: ${TESTING_MODE}
    depends_on:
      - db
  werewolf-library-install:
    extends:
      service: werewolf-bot
    command: ./watch-install.sh
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-db: