version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_HOST
  build:
    commands:
      - export IMAGE_TAG="$REPO:$TAG"
      - echo "Building containers image"
      - docker build -t $IMAGE_TAG -f Build.Dockerfile .
  post_build:
    commands:
      - echo "Pushing $IMAGE_TAG"
      - docker push "$IMAGE_TAG"
      - |
        echo "Restarting application"
        aws ssm send-command \
          --document-name "$DEPLOY_DOCUMENT" \ 
          --targets "" \
          --parameters "${parameters_argument}"
          --timeout-seconds 600 \
          --region "$AWS_REGION"
